username: luciaknud
app-id: com.instagram.android
allow-untested-ig-version: true
screen-sleep: false
debug: true
shuffle-jobs: true
truncate-sources: 2-3
feed: 2-5
interactions-count: 5-10
likes-count: 1-2
likes-percentage: 100
stories-count: 0
stories-percentage: 0
carousel-count: 1
carousel-percentage: 50
watch-video-time: 3-8
watch-photo-time: 1-4
interact-percentage: 50
follow-percentage: 0
follow-limit: 5
skipped-list-limit: 5-10
skipped-posts-limit: 3
fling-when-skipped: 0
min-following: 100
total-likes-limit: 50
total-follows-limit: 50
total-unfollows-limit: 50
total-watches-limit: 50
total-successful-interactions-limit: 50
total-interactions-limit: 100
total-comments-limit: 50
total-pm-limit: 50
total-scraped-limit: 50
end-if-likes-limit-reached: true
end-if-follows-limit-reached: true
working-hours: [0.00-23.59]
time-delta: 0
total-sessions: 1
