username: luciaknud
app-id: com.instagram.android
allow-untested-ig-version: true
screen-sleep: false
debug: true
shuffle-jobs: true
truncate-sources: 2-3
feed: 2-5
interactions-count: 5-10
likes-count: 1-2
likes-percentage: 100
stories-count: 0
stories-percentage: 0
carousel-count: 1
carousel-percentage: 50
watch-video-time: 10-15
watch-photo-time: 3-5
interact-percentage: 50
follow-percentage: 0
follow-limit: 5
skipped-list-limit: 5-10
skipped-posts-limit: 3
fling-when-skipped: 0
min-following: 100
total-likes-limit: 10
total-follows-limit: 0
total-unfollows-limit: 10
total-watches-limit: 5
total-successful-interactions-limit: 10
total-interactions-limit: 20
total-comments-limit: 0
total-pm-limit: 0
total-scraped-limit: 50
end-if-likes-limit-reached: true
end-if-follows-limit-reached: true
working-hours: [9.00-12.00, 14.00-17.00, 19.00-22.00]
time-delta: 10-20
total-sessions: 1
